---
title: "chap11_facets"
author: "J.H AHN"
date: '2022 1 11 '
output: html_document
---

```{r setup, include=FALSE}
library(gcookbook)
library(tidyverse)
library(patchwork)

knitr::opts_chunk$set(echo = TRUE)
```

<br>
<br>
### 11.1 Splitting data into subplots with facets
<br>

<br>
```{r fig_11_1}
fig_11011 <- 
  mpg %>% 
  ggplot(aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ .) +
  labs(subtitle = "facet by drv")

fig_11012 <- 
  mpg %>% 
  ggplot(aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(. ~ cyl) +
  labs(subtitle = "facet by cyl")

fig_11013 <- 
  mpg %>% 
  ggplot(aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ cyl)

plot_spacer() + fig_11012 + fig_11011 + fig_11013 + plot_layout(widths = c(1,4), heights = c(1,3))

```


<br>
```{r}
mpg %>% 
  ggplot(aes(x = displ, y = hwy)) +
  geom_point() +
  facet_wrap(~ class)

```


<br>
<br>
### 11.2 Using facets with different axes
<br>

<br>
```{r fig_11_2}
fig_11021 <- 
  mpg %>% 
  ggplot(aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ cyl, scales = "free_y") +
  labs(subtitle = "with free y scales")

fig_11022 <- 
  mpg %>% 
  ggplot(aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ cyl, scales = "free") +
  labs(subtitle = "with free both scales")

fig_11021 + fig_11022

```


<br>
<br>
### 11.3 Changing the text of facet labels
<br>

<br>
```{r}
mpg2 <- mpg

mpg2 <- 
  mpg2 %>% 
  mutate(drv = case_when(drv == "4" ~ "4wd",
                         drv == "f" ~ "Front",
                         TRUE ~ "Rear"))

```


<br>
```{r fig_11_4}
fig_11041 <- 
  mpg %>% 
  ggplot(aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ .) +
  labs(subtitle = "default facet label")

fig_11042 <- 
  mpg2 %>% 
  ggplot(aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ .) +
  labs(subtitle = "modified facet label")

fig_11041 + fig_11042

```


<br>
`facet_grid()`나 `facet_wrap()`은 `labeller()`함수를 사용하여 label을 정할 수 있다.  
이 labeller에 있는 `label_both()`는 변수의 이름과 값을 각각의 facet에 label로 출력해준다.  
<br>
```{r}
mpg3 <- mpg

mpg3 <- 
  mpg3 %>%
  mutate(drv = case_when(drv == "4" ~ "4^{wd}",
                         drv == "f" ~ "- Front %.% e^{pi*i}",
                         TRUE ~ "4^{wd} - Front"))

```


```{r fig_11_5}
fig_11051 <- 
  mpg2 %>% 
  ggplot(aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ ., labeller = label_both) +
  labs(subtitle = "label_both")

fig_11052 <- 
  mpg3 %>% 
  ggplot(aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ ., labeller = label_parsed) +
  labs(subtitle = "label_parse")

fig_11051 + fig_11052

```


<br>
<br>
### 11.4 Changing appearance of facet labels and headers
<br>

<br>
size=1의 의미는 사각형에 1mm 두께의 외곽선을 그리라는 것  
<br>
```{r fig_11_6}
cabbage_exp %>% 
  ggplot(aes(x = Cultivar, y = Weight)) +
  geom_bar(stat = "identity") +
  facet_grid(. ~ Date) +
  theme(strip.text = element_text(face = "bold", size = rel(1.5)),
        strip.background = element_rect(fill = "#90ee90", color = "#000000", size = 1))


```




<br>
<br>
<br>


**END**


<br>
<br>
<br>